version: 2

jobs:
  deploy-docs:
    docker:
    - image: python:3.8
    steps:
      - run:
          name: Install core dependencies
          command: |
            apt-get update
            apt-get install -y git g++ gcc make

      - checkout

      - run:
          name: Install documentation dependencies
          command: |
            pip install --no-cache-dir -r ./requirements.txt

      - run:
          name: Deploy documentation
          command: |
            git config --global user.name "CircleCI ( ${CIRCLE_USERNAME} )"
            git config --global user.email "${CIRCLE_USERNAME}@${CIRCLE_BRANCH}"
            ./deploy.sh git@github.com:dccs-tech/us-bylaws.git "${CIRCLE_BRANCH}"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-docs:
          filters:
            branches:
              only:
                - master